(ns galaticos.db.protocol.championship-store
  "Persistence contract for championships and related seasons/players.")

(defprotocol ChampionshipStore
  (find-all-championships [this])
  (find-championship-by-id [this id])
  (create-championship [this doc])
  (update-championship-by-id [this id updates])
  (delete-championship-by-id [this id])
  (championship-exists? [this id])
  (championship-has-matches? [this id])
  (add-player-to-championship [this championship-id player-id])
  (remove-player-from-championship [this championship-id player-id])
  (find-all-seasons-by-championship [this championship-id])
  (find-active-season-by-championship [this championship-id])
  (create-season [this doc])
  (update-season-by-id [this id updates])
  (delete-seasons-by-championship [this championship-id])
  (activate-season! [this season-id])
  (finalize-season! [this season-id winner-player-ids titles-award-count])
  (add-player-to-season [this season-id player-id])
  (remove-player-from-season [this season-id player-id])
  (find-player-by-id [this player-id])
  (find-players-by-ids [this player-ids])
  (increment-player-titles [this player-ids amount])
  (enrolled-player-object-ids [this championship-id]))
